import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { z } from "zod";
import { useState } from "react";
import { ArrowLeft, Database } from "lucide-react";
import { Button } from "@/components/ui/button";
import { signInWithGoogle } from "@/lib/auth";
const searchSchema=z.object({mode:z.enum(["login","signup"]).catch("login")});
export const Route=createFileRoute("/auth")({validateSearch:s=>searchSchema.parse(s),head:()=>({meta:[{title:"Account access — pg-router-ai"},{name:"description",content:"Sign in to your pg-router-ai workspace with Google."},{property:"og:title",content:"Account access — pg-router-ai"},{property:"og:description",content:"Secure access to your PostgreSQL control plane."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Auth});
function Auth(){const navigate=useNavigate(),initial=Route.useSearch().mode;const[mode,setMode]=useState<"login"|"signup">(initial),[error,setError]=useState(""),[busy,setBusy]=useState(false);
async function google(){setError("");setBusy(true);try{const user=await signInWithGoogle();if(user)await navigate({to:"/dashboard"});}catch(x){setError(x instanceof Error?x.message:"Unable to continue");}finally{setBusy(false)}}
return <div className="mosaic grid min-h-screen md:grid-cols-[1fr_1fr]"><aside className="hidden border-r p-10 md:flex md:flex-col md:justify-between"><Link to="/" className="flex items-center gap-3 font-display font-bold"><span className="grid size-8 place-items-center bg-primary text-primary-foreground"><Database className="size-4"/></span>pg-router-ai</Link><h1 className="font-display text-6xl font-bold leading-[.9] text-primary">Controlled access.<br/>Observable systems.</h1><div className="tech-label">AUTH GATEWAY / TLS REQUIRED / SESSION ROTATION</div></aside><main className="flex items-center justify-center p-5"><div className="relative w-full max-w-[520px] border bg-background p-6 md:p-10"><i className="corner-marker left-[-1px] top-[-1px]"/><i className="corner-marker right-[-1px] top-[-1px] rotate-90"/><Link to="/" className="mb-10 inline-flex items-center gap-2 tech-label"><ArrowLeft className="size-3"/> Return home</Link><div className="mb-8 flex border-b"><Button variant="ghost" className={`flex-1 border-b-2 py-3 tech-label ${mode==="login"?"border-primary":"border-transparent text-muted-foreground"}`} onClick={()=>setMode("login")}>Sign in</Button><Button variant="ghost" className={`flex-1 border-b-2 py-3 tech-label ${mode==="signup"?"border-primary":"border-transparent text-muted-foreground"}`} onClick={()=>setMode("signup")}>Create account</Button></div><span className="tech-label text-primary">GOOGLE OAUTH / 01</span><h2 className="mt-3 font-display text-3xl font-bold">{mode==="signup"?"Create your workspace":"Welcome back"}</h2><p className="mt-2 text-sm text-muted-foreground">{mode==="signup"?"Your workspace is created automatically on first Google sign-in.":"Access your database control plane with your Google account."}</p><div className="mt-8 space-y-5"><Button className="w-full" size="lg" disabled={busy} onClick={google}><GoogleIcon/>{busy?"Redirecting to Google…":"Continue with Google"}</Button>{error&&<p className="border-l-2 border-destructive pl-3 text-sm text-destructive">{error}</p>}<p className="tech-label text-muted-foreground">SINGLE SIGN-ON ONLY / NO PASSWORDS STORED</p></div></div></main></div>}
function GoogleIcon(){return <svg className="size-4" viewBox="0 0 24 24" aria-hidden><path fill="currentColor" d="M21.35 11.1h-9.17v2.73h6.51c-.33 3.81-3.5 5.44-6.5 5.44C8.36 19.27 5 16.25 5 12c0-4.1 3.2-7.27 7.2-7.27 3.09 0 4.9 1.97 4.9 1.97L19 4.72S16.56 2 12.1 2C6.42 2 2.03 6.8 2.03 12c0 5.05 4.13 10 10.22 10 5.35 0 9.25-3.67 9.25-9.09 0-1.15-.15-1.81-.15-1.81Z"/></svg>}
