import { BedrockRuntimeClient, ConverseCommand } from "@aws-sdk/client-bedrock-runtime";
import { aiEnabled } from "../config/ai";
import { parseQuery } from "../router/parser";
import { simulatedSchemaDescription } from "../router/simulated-driver";
import type { NLQueryResult } from "../types/ai";
import { AIError } from "../utils/errors";
import { logger } from "../utils/logger";
import { assertSafeSql } from "../utils/validators";
import { extractJson, generateText } from "./gemini-client";

const SYSTEM_INSTRUCTION = `You translate natural language questions into a single PostgreSQL statement.
Return ONLY JSON: {"sql":string,"confidence":number,"explanation":string}
Rules: one statement, no trailing semicolon issues, never DROP/TRUNCATE/ALTER, always add a LIMIT to open-ended SELECTs,
use only tables and columns present in the provided schema, and use $1-style placeholders for user-supplied values.`;

export interface ValidationOutcome {
  valid: boolean;
  errors: string[];
  routing: "primary" | "replica";
}

export const validateGeneratedSQL = (sql: string): ValidationOutcome => {
  const errors: string[] = [];
  try {
    assertSafeSql(sql);
  } catch (error) {
    errors.push(error instanceof Error ? error.message : String(error));
  }

  let routing: "primary" | "replica" = "replica";
  try {
    const parsed = parseQuery(sql);
    routing = parsed.isWrite ? "primary" : "replica";
    if (parsed.type === "UNKNOWN") errors.push("Could not determine the statement type");
    if (parsed.type === "DDL") errors.push("DDL statements are not allowed from natural language");
    if (!parsed.tables.length && parsed.type === "SELECT") errors.push("No tables referenced");
  } catch (error) {
    errors.push(error instanceof Error ? error.message : String(error));
  }

  return { valid: errors.length === 0, errors, routing };
};

// ---------------------------------------------------------------------------
// DeepSeek Bedrock NL→SQL (primary engine — already configured)
// ---------------------------------------------------------------------------
const region = process.env.AWS_REGION || "us-east-1";
const accessKeyId = process.env.AWS_ACCESS_KEY_ID;
const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
const modelId = process.env.BEDROCK_MODEL_ID || "deepseek.v3.2";

const isBedrockReady = (): boolean => Boolean(accessKeyId && secretAccessKey);

let _bedrockClient: BedrockRuntimeClient | null = null;
const getBedrockClient = (): BedrockRuntimeClient => {
  if (!_bedrockClient) {
    _bedrockClient = new BedrockRuntimeClient({
      region,
      credentials: { accessKeyId: accessKeyId!, secretAccessKey: secretAccessKey! },
    });
  }
  return _bedrockClient;
};

const convertWithBedrock = async (
  question: string,
  schemaContext: string,
): Promise<{ sql: string; confidence: number; explanation: string }> => {
  const prompt = `You are a PostgreSQL expert. Convert the following natural language question into a single valid SQL statement for the given schema.

Schema:
${schemaContext}

Question: ${question}

Return ONLY a JSON object with exactly these fields:
{"sql": "SELECT ...", "confidence": 0.95, "explanation": "Brief explanation"}

Rules:
- One statement only, no semicolon
- Never use DROP, TRUNCATE, or ALTER
- Always add LIMIT 100 to open-ended SELECTs
- Use only tables and columns from the schema above
- If the schema is a sample/demo, use plausible table names like users, orders, products`;

  const command = new ConverseCommand({
    modelId,
    messages: [{ role: "user", content: [{ text: prompt }] }],
    inferenceConfig: { maxTokens: 512, temperature: 0.15 },
  });

  const response = await getBedrockClient().send(command);
  const content = response.output?.message?.content?.[0]?.text ?? "";

  if (!content) throw new AIError("DeepSeek Bedrock returned an empty response for NL→SQL");

  const jsonMatch = content.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new AIError("DeepSeek Bedrock did not return valid JSON for NL→SQL");

  const parsed = JSON.parse(jsonMatch[0]) as { sql?: string; confidence?: number; explanation?: string };
  const sql = (parsed.sql ?? "").trim().replace(/;$/, "");
  if (!sql) throw new AIError("DeepSeek Bedrock did not produce SQL");

  return {
    sql,
    confidence: Math.max(0, Math.min(1, parsed.confidence ?? 0.8)),
    explanation: parsed.explanation ?? "Generated by DeepSeek via AWS Bedrock",
  };
};

// ---------------------------------------------------------------------------
// Public: convertToSQL — tries Bedrock first, falls back to Gemini
// ---------------------------------------------------------------------------
export const convertToSQL = async (question: string, schema?: string): Promise<NLQueryResult> => {
  const schemaContext = schema?.trim() || simulatedSchemaDescription;

  let sql: string;
  let confidence: number;
  let explanation: string;

  if (isBedrockReady()) {
    // Primary path: DeepSeek via AWS Bedrock (no API key needed, uses IAM creds)
    try {
      logger.info("NL→SQL: using DeepSeek Bedrock", { question: question.slice(0, 80) });
      const result = await convertWithBedrock(question, schemaContext);
      sql = result.sql;
      confidence = result.confidence;
      explanation = result.explanation;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.warn("DeepSeek Bedrock NL→SQL failed, trying Gemini fallback", { error: msg });

      if (!aiEnabled.gemini()) {
        throw new AIError(`NL→SQL failed (Bedrock: ${msg}). Set GEMINI_API_KEY for a fallback.`);
      }
      // Gemini fallback
      const prompt = `Schema:\n${schemaContext}\n\nQuestion: ${question}`;
      const text = await generateText(prompt, SYSTEM_INSTRUCTION);
      const parsed = extractJson<{ sql?: string; confidence?: number; explanation?: string }>(text);
      sql = (parsed.sql ?? "").trim();
      confidence = parsed.confidence ?? 0.5;
      explanation = parsed.explanation ?? "";
    }
  } else if (aiEnabled.gemini()) {
    // Gemini-only path (Bedrock not configured)
    logger.info("NL→SQL: using Gemini (Bedrock not configured)", { question: question.slice(0, 80) });
    const prompt = `Schema:\n${schemaContext}\n\nQuestion: ${question}`;
    const text = await generateText(prompt, SYSTEM_INSTRUCTION);
    const parsed = extractJson<{ sql?: string; confidence?: number; explanation?: string }>(text);
    sql = (parsed.sql ?? "").trim();
    confidence = parsed.confidence ?? 0.5;
    explanation = parsed.explanation ?? "";
  } else {
    throw new AIError(
      "Natural language to SQL requires either AWS Bedrock credentials (AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY) or GEMINI_API_KEY to be configured.",
    );
  }

  if (!sql) throw new AIError("AI model did not return SQL");

  const validation = validateGeneratedSQL(sql);
  if (!validation.valid) {
    logger.warn("Generated SQL failed validation", { errors: validation.errors });
  }

  return {
    question,
    sql,
    confidence: Math.max(0, Math.min(1, confidence)),
    explanation,
    routing: validation.routing,
    valid: validation.valid,
    validationErrors: validation.errors,
  };
};
