import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Quote, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NetworkTopology, PublicHeader, SiteFooter, StatusBadge, TrustMark } from "@/components/PublicShell";

const features = [
  { n: "01", title: "INTELLIGENT ROUTING", accent: "border-accent-coral", body: "Reads find the healthiest replica. Transactions stay pinned. Failover is immediate.", mock: ["SELECT * FROM events", "→ replica-02 / 4.2ms"] },
  { n: "02", title: "QUERY INTELLIGENCE", accent: "border-accent-mint", body: "Explain plans become clear, actionable decisions with AI-assisted optimization.", mock: ["SEQUENTIAL SCAN / users", "+ INDEX users_email_idx"] },
  { n: "03", title: "ANOMALY SIGNAL", accent: "border-accent-gold", body: "Catch latency spikes, N+1 patterns and unseen query shapes before users notice.", mock: ["ANOMALY SCORE 0.92", "PATTERN / N+1 DETECTED"] },
  { n: "04", title: "DETERMINISTIC REPLAY", accent: "border-primary", body: "Capture production traffic and replay it safely at controlled speeds.", mock: ["2,418 queries captured", "REPLAY 10× / 98% MATCH"] },
];

export function LandingPage() {
  return <div className="mosaic min-h-screen bg-background text-foreground"><PublicHeader/>
    <main className="pt-16">
      <section className="border-b"><div className="mx-auto grid min-h-[calc(100svh-64px)] max-w-[1440px] md:grid-cols-[1.25fr_.75fr]">
        <div className="flex flex-col justify-between px-4 py-10 md:border-r md:px-8 md:py-16">
          <StatusBadge/>
          <div className="my-16 md:my-24"><p className="mb-6 border-l border-primary pl-4 font-mono text-xs uppercase text-primary md:text-sm">PostgreSQL routing / observability / intelligence</p><h1 className="max-w-5xl font-display text-[clamp(3.5rem,8vw,7.5rem)] font-bold leading-[.86] text-primary">Every query.<br/>Precisely routed.</h1><p className="mt-8 max-w-xl text-base leading-relaxed text-muted-foreground md:text-lg">One control plane to route, inspect and replay PostgreSQL traffic—without changing application code.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/auth" search={{ mode: "signup" }}>Start free <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><Link to="/product">Explore system</Link></Button></div></div>
          <div className="flex flex-wrap items-center gap-6 border-t pt-5"><TrustMark/><span className="tech-label text-muted-foreground">JWT SESSION ROTATION</span><span className="tech-label text-muted-foreground">OTP VERIFIED</span></div>
        </div>
        <div className="flex items-center justify-center border-t p-5 md:border-t-0 md:p-8"><NetworkTopology/></div></div>
      </section>
      <section className="border-b"><div className="mx-auto max-w-[1440px] px-4 py-16 md:px-8 md:py-24"><div className="mb-10 grid gap-6 md:grid-cols-2"><div><span className="tech-label text-primary">SYSTEM / CAPABILITIES</span><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold leading-none md:text-6xl">Infrastructure you can reason about.</h2></div><p className="max-w-lg self-end text-muted-foreground">Flat, inspectable, and built for operators. Every routing decision carries context and every signal remains traceable.</p></div><div className="grid gap-px border bg-grid md:grid-cols-2">{features.map(f => <article key={f.n} className="bg-background p-6 md:p-8"><div className={`border-l-2 pl-3 tech-label ${f.accent}`}>{f.n} / {f.title}</div><h3 className="mt-8 font-display text-2xl font-bold">{f.title.replaceAll("_", " ")}</h3><p className="mt-3 max-w-md text-sm leading-relaxed text-muted-foreground">{f.body}</p><div className="mt-8 border bg-surface p-4 font-mono text-xs"><div className="mb-3 flex gap-1"><span className="size-2 bg-accent-coral"/><span className="size-2 bg-accent-gold"/><span className="size-2 bg-accent-mint"/></div><div>{f.mock[0]}</div><div className="mt-2 text-primary">{f.mock[1]}</div></div></article>)}</div></div></section>
      <section className="border-b"><div className="mx-auto grid max-w-[1440px] md:grid-cols-2"><div className="p-6 md:border-r md:p-12"><span className="tech-label">OPERATOR NOTE / 028</span><Quote className="mt-10 size-8 text-primary"/><div className="mt-4 flex gap-1">{[1,2,3,4,5].map(n=><Star key={n} className="size-3 fill-accent-gold text-accent-gold"/>)}</div><blockquote className="mt-6 max-w-xl font-mono text-sm leading-7">“We stopped guessing which replica was hurting us. The routing map made the bottleneck obvious in under five minutes.”</blockquote><div className="mt-10 flex items-center gap-3 border-t pt-5"><div className="grid size-10 place-items-center bg-primary font-mono text-xs text-primary-foreground">AK</div><div><div className="font-mono text-xs font-bold">ALEX KIM</div><div className="tech-label text-muted-foreground">PLATFORM ENGINEER / NORTHSTAR</div></div></div></div><div className="p-6 md:p-12"><div className="relative border bg-background p-6 md:p-10"><i className="corner-marker left-[-1px] top-[-1px]"/><i className="corner-marker right-[-1px] top-[-1px] rotate-90"/><i className="corner-marker bottom-[-1px] right-[-1px] rotate-180"/><i className="corner-marker bottom-[-1px] left-[-1px] -rotate-90"/><span className="tech-label text-primary">REQUEST ACCESS / 001</span><h2 className="mt-4 font-display text-3xl font-bold">Route your first query.</h2><p className="mt-2 text-sm text-muted-foreground">Create a verified workspace in less than two minutes.</p><ul className="my-8 space-y-3 font-mono text-xs">{["14-day evaluation", "No card required", "Full replay access"].map(x=><li key={x} className="flex items-center gap-2"><Check className="size-4 text-primary"/>{x}</li>)}</ul><Button asChild className="w-full"><Link to="/auth" search={{mode:"signup"}}>Create workspace <ArrowRight/></Link></Button></div></div></div></section>
    </main><SiteFooter/></div>;
}
